### ISSUE TITLE
Failed building wheel for xxx

### ISSUE THREAD

**Issue by Slian22** [ish-app/ish#1211]
When i download the package from python.It appear that:
```

Building wheel for regex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dwxn0_8d/regex_4ce35a7b31634f97be6dc0a5b40483df/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dwxn0_8d/regex_4ce35a7b31634f97be6dc0a5b40483df/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-m7p0v12a
       cwd: /tmp/pip-install-dwxn0_8d/regex_4ce35a7b31634f97be6dc0a5b40483df/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-3.8
  creating build/lib.linux-i686-3.8/regex
  copying regex_3/__init__.py -> build/lib.linux-i686-3.8/regex
  copying regex_3/regex.py -> build/lib.linux-i686-3.8/regex
  copying regex_3/_regex_core.py -> build/lib.linux-i686-3.8/regex
  copying regex_3/test_regex.py -> build/lib.linux-i686-3.8/regex
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-i686-3.8
  creating build/temp.linux-i686-3.8/regex_3
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-i686-3.8/regex_3/_regex.o
  regex_3/_regex.c:50:10: fatal error: Python.h: No such file or directory
     50 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex
  Running setup.py clean for regex

```

**Comment by Slian22** [comment]
How can I fix it?

**Comment by tbodt** [comment]
apk add python3-dev

**Comment by Slian22** [comment]
but it still remains that:
```
Building wheel for regex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dwxn0_8d/regex_4ce35a7b31634f97be6dc0a5b40483df/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dwxn0_8d/regex_4ce35a7b31634f97be6dc0a5b40483df/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-m7p0v12a
       cwd: /tmp/pip-install-dwxn0_8d/regex_4ce35a7b31634f97be6dc0a5b40483df/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-3.8
  creating build/lib.linux-i686-3.8/regex
  copying regex_3/__init__.py -> build/lib.linux-i686-3.8/regex
  copying regex_3/regex.py -> build/lib.linux-i686-3.8/regex
  copying regex_3/_regex_core.py -> build/lib.linux-i686-3.8/regex
  copying regex_3/test_regex.py -> build/lib.linux-i686-3.8/regex
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-i686-3.8
  creating build/temp.linux-i686-3.8/regex_3
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-i686-3.8/regex_3/_regex.o
  regex_3/_regex.c:50:10: fatal error: Python.h: No such file or directory
     50 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex
  Running setup.py clean for regex

```

**Comment by Slian22** [comment]
but it still remains that:
```
building 'psutil._psutil_linux' extension
  creating build/temp.linux-i686-3.8
  creating build/temp.linux-i686-3.8/psutil
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.8 -c psutil/_psutil_common.c -o build/temp.linux-i686-3.8/psutil/_psutil_common.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.8 -c psutil/_psutil_posix.c -o build/temp.linux-i686-3.8/psutil/_psutil_posix.o
  psutil/_psutil_posix.c:30:14: fatal error: linux/types.h: No such file or directory
     30 |     #include <linux/types.h>
        |              ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil

```

**Comment by tbodt** [comment]
apk add build-base

**Comment by Slian22** [comment]
anything else?

**Comment by Slian22** [comment]
but problem is still remains that:
```
Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-utm1xpvf/psutil_165420ed88d649eb95b2a49c1063790e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-utm1xpvf/psutil_165420ed88d649eb95b2a49c1063790e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z3dzc5p6
       cwd: /tmp/pip-install-utm1xpvf/psutil_165420ed88d649eb95b2a49c1063790e/
  Complete output (50 lines):
  /tmp/tmptuojbncr.c:1:10: fatal error: linux/ethtool.h: No such file or directory
      1 | #include <linux/ethtool.h>
        |          ^~~~~~~~~~~~~~~~~
  compilation terminated.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-3.8
  creating build/lib.linux-i686-3.8/psutil
  copying psutil/_pswindows.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_common.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/__init__.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_psosx.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_psbsd.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_psaix.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_pslinux.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_compat.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_psposix.py -> build/lib.linux-i686-3.8/psutil
  copying psutil/_pssunos.py -> build/lib.linux-i686-3.8/psutil
  creating build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/runner.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-i686-3.8/psutil/tests
copying psutil/tests/test_unicode.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_memleaks.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-i686-3.8/psutil/tests
  copying psutil/tests/test_testutils.py -> build/lib.linux-i686-3.8/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-i686-3.8
  creating build/temp.linux-i686-3.8/psutil
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.8 -c psutil/_psutil_common.c -o build/temp.linux-i686-3.8/psutil/_psutil_common.o
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.8 -c psutil/_psutil_posix.c -o build/temp.linux-i686-3.8/psutil/_psutil_posix.o
  psutil/_psutil_posix.c:30:14: fatal error: linux/types.h: No such file or directory
     30 |     #include <linux/types.h>
        |              ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil

```

**Comment by Slian22** [comment]
How can I fix it?

**Comment by tbodt** [comment]
Looks like you'll also need `apk add linux-headers`

**Comment by Slian22** [comment]
Thanks for your help,I will try it.

**Comment by Slian22** [comment]
well,the problem updates.
```
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eaf1a9or/pillow_8309d1bddc894db78e65b314754377d3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eaf1a9or/pillow_8309d1bddc894db78e65b314754377d3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-u339f0ef
       cwd: /tmp/pip-install-eaf1a9or/pillow_8309d1bddc894db78e65b314754377d3/
  Complete output (172 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-3.8
  creating build/lib.linux-i686-3.8/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-i686-3.8/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-i686-3.8/PIL
   The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-eaf1a9or/pillow_8309d1bddc894db78e65b314754377d3/setup.py", line 861, in <module>
      setup(
    File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-eaf1a9or/pillow_8309d1bddc894db78e65b314754377d3/setup.py", line 698, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-eaf1a9or/pillow_8309d1bddc894db78e65b314754377d3/setup.py", line 914, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  ----------------------------------------
  ERROR: Failed building wheel for Pillow
```

**Comment by tbodt** [comment]
Seems you will need `apk add zlib-dev`

**Comment by Slian22** [comment]
well,it appears that:
The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-fgp9pakf/pillow_a7cb86e74ec04d9592816dc9aa8bfeec/setup.py", line 861, in <module>
        setup(
      File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-fgp9pakf/pillow_a7cb86e74ec04d9592816dc9aa8bfeec/setup.py", line 698, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fgp9pakf/pillow_a7cb86e74ec04d9592816dc9aa8bfeec/setup.py", line 914, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
     During handling of the above exception, another exception occurred:
 
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fgp9pakf/pillow_a7cb86e74ec04d9592816dc9aa8bfeec/setup.py", line 914, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fgp9pakf/pillow_a7cb86e74ec04d9592816dc9aa8bfeec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fgp9pakf/pillow_a7cb86e74ec04d9592816dc9aa8bfeec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wf5c_q9e/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/Pillow Check the logs for full command output.
