### ISSUE TITLE
`python -m install pycurl` hangs indefinitely

### ISSUE THREAD

**Issue by flexabyte** [ish-app/ish#1254]
I’ve been playing around with installing different python modules and I’ve discovered that pycurl doesn’t install. It hangs (from what I can tell) indefinitely. Most probably a race condition similar to the ones we’ve seen from building go modules in [issue 1230](https://github.com/ish-app/ish/issues/1230). 

Now, I’ve not had a chance to debug this, I only just got introduced to this project and need to actually get it compiling first (I’ll try over the weekend), but here is my call stack when I eventually kill the process:

```
^CTraceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/pip/__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 7, in <module>
    from pip._vendor import six
  File "/usr/lib/python3.8/site-packages/pip/_vendor/__init__.py", line 77, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python3.8/site-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('packaging.requirements')
  File "/usr/lib/python3.8/site-packages/packaging/requirements.py", line 9, in <module>
    from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 911, in get_code
  File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
```

So it appears to hang in the `_compile_bytecode` function, could potentially be caused by the JIT compiler, which could be a big problem to solve but I’ll update once I get a chance to debug it. Just wanted to share in case anyone has seen similar issues.

Thanks

**Comment by Mnpn03** [comment]
I can't reproduce this. It takes a little while to install, but it isn't too bad.
<img src="https://user-images.githubusercontent.com/17569187/115060048-ac488580-9ee7-11eb-894c-7d2b27d729d6.PNG" width="40%" height="auto" />
How long did you wait, could you try it again?

**Comment by flexabyte** [comment]
I just tried this again and it appears to be working if you wait long enough.

Thanks, closing.
