### ISSUE TITLE
Ptpython install fails

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#1413]
I tried to install ptpython but got:

Using legacy setup.py install for regex, since package 'wheel' is not installed.
Installing collected packages: pygments, parso, jedi, pathspec, regex, mypy-extensions, black, ptpython
    Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vf_q2dcw/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vf_q2dcw/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jlbztaw0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/regex
         cwd: /tmp/pip-install-vf_q2dcw/regex/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-3.8
    creating build/lib.linux-i686-3.8/regex
    copying regex_3/__init__.py -> build/lib.linux-i686-3.8/regex
    copying regex_3/regex.py -> build/lib.linux-i686-3.8/regex
    copying regex_3/_regex_core.py -> build/lib.linux-i686-3.8/regex
    copying regex_3/test_regex.py -> build/lib.linux-i686-3.8/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-i686-3.8
    creating build/temp.linux-i686-3.8/regex_3
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c regex_3/_regex.c -o build/temp.linux-i686-3.8/regex_3/_regex.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vf_q2dcw/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vf_q2dcw/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jlbztaw0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/regex Check the logs for full command output.

**Comment by 62f** [comment]
```apk add gcc sudo```
Then create and switch to a subordinate user account from which to run pip installs.

**Comment by ifuchs** [comment]
Thanks but that fails as shown:

    Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'/tmp/pip-install-uug5haup/regex/setup.py'"'"';
__file__='"'"'/tmp/pip-install-uug5haup/regex/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-zz7g2rou/install-record.txt
--single-version-externally-managed --compile --install-headers
/usr/include/python3.8/regex
         cwd: /tmp/pip-install-uug5haup/regex/
    Complete output (21 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-3.8
    creating build/lib.linux-i686-3.8/regex
    copying regex_3/__init__.py -> build/lib.linux-i686-3.8/regex
    copying regex_3/regex.py -> build/lib.linux-i686-3.8/regex
    copying regex_3/_regex_core.py -> build/lib.linux-i686-3.8/regex
    copying regex_3/test_regex.py -> build/lib.linux-i686-3.8/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-i686-3.8
    creating build/temp.linux-i686-3.8/regex_3
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall
-fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g
-fno-semantic-interposition -fomit-frame-pointer -g
-fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC
-I/usr/include/python3.8 -c regex_3/_regex.c -o
build/temp.linux-i686-3.8/regex_3/_regex.o
    In file included from regex_3/_regex.c:50:
    /usr/include/python3.8/Python.h:11:10: fatal error: limits.h: No such
file or directory
       11 | #include <limits.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-uug5haup/regex/setup.py'"'"';
__file__='"'"'/tmp/pip-install-uug5haup/regex/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-zz7g2rou/install-record.txt
--single-version-externally-managed --compile --install-headers
/usr/include/python3.8/regex Check the logs for full command output.

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/119221001-2a85e200-babb-11eb-9368-14f89d73662a.jpeg)
For some reason your pip rejected the apks I had requested to manually install or the py3-foo.apk isn't included anymore; ie. possibly that py3-foo isn't still included in the repository, so the add failed and you didn't notice. For my pip install above I had run my ```apk add foo``` from iSH's oldest & largest available date due to my having noticed that our total packages count-up number has been numerically-diminishing for each new build.

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/120415427-835e4180-c329-11eb-802e-6c1b88c94ec1.jpeg)
Alpine was having a hard time, after a fresh update from TestFlight, at locating the tar.gz of the updated repositories. Suggest: blindly or automatically running ```apk fix``` after every iSH-install.

**Comment by ifuchs** [comment]
ptpython will now install successfully; however, after starting it and beginning to type at the >>> prompt seems to hang ish. It may be that CPR (Cursor Positioning Report) is not implemented or perhaps a performance issue. Has anyone tried to get it working?

**Comment by 62f** [comment]
ɎɆ₱ ł ₮ⱤîɆđ
# ```which ptpython```
/usr/bin/ptpython
iPhone:~# ```ptpython```
Traceback (most recent call last):
  File "/usr/bin/ptpython", line 5, in <module>
    from ptpython.entry_points.run_ptpython import run
  File "/usr/lib/python3.8/site-packages/ptpython/__init__.py", line 1, in <module>
    from .repl import embed
  File "/usr/lib/python3.8/site-packages/ptpython/repl.py", line 21, in <module>
    from prompt_toolkit.formatted_text import (
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
