### ISSUE TITLE
Pip doesn't works

### ISSUE THREAD

**Issue by FireBibi** [ish-app/ish#1696]
Hello so if I try to execute `pip` it doesn't do anything but when I use ctrl + c to stop the command I get this error : ```

^CTraceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip')())
  File "/usr/bin/pip", line 25, in importlib_load_entry_point
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 6, in <module>
    import logging
  File "/usr/lib/python3.9/logging/__init__.py", line 28, in <module>
    from string import Template
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 851, in exec_module
  File "<frozen importlib._bootstrap_external>", line 963, in get_code
  File "<frozen importlib._bootstrap_external>", line 1045, in get_data
```
Also if I wait more the error gets bigger.

**Comment by xloem** [comment]
This is so slow (I haven’t seen any output from pip yet) that I am using this which is much faster:
alias pip="python3 -c 'from setuptools import setup; setup()' easy_install"
