### ISSUE TITLE
install pandas and numpy for python3?

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#1698]
I have tried unsuccessfully to install numpy and pandas using both apk (says machine needs SSE) and pip (hangs). Has anyone found a way to install these python packages?

**Comment by xloem** [comment]
I’m trying this out to use the old versions without downgrading the whole system. Note that alpine is up to v3.16 now.
```
# add 3.13 repos, keeping 3.14
echo https://dl-cdn.alpinelinux.org/alpine/v3.13/main >> /etc/apk/repositories
echo https://dl-cdn.alpinelinux.org/alpine/v3.13/community >> /etc/apk/repositories
apk update
apk del --rdepends python3 # removes everything using python3.9
apk add python3\<3.9 py3-numpy\<1.20 py3-pip # installs python3.8
```

**Comment by cbrown1** [comment]
This fixes numpy, but it appears to break pip:

`# pip -v
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip')())
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pip
SHRSF76Y4Q7N7H:~# `

**Comment by xloem** [comment]
I never finished trying that workaround and it likely needs further development. Note that pip doesn’t work for me regardless, and I use easy_install instead: https://github.com/ish-app/ish/issues/1696#issuecomment-1152238005

**Comment by behthr** [comment]
> I’m trying this out to use the old versions without downgrading the whole system. Note that alpine is up to v3.16 now.
> 
> ```
> # add 3.13 repos, keeping 3.14
> echo https://dl-cdn.alpinelinux.org/alpine/v3.13/main >> /etc/apk/repositories
> echo https://dl-cdn.alpinelinux.org/alpine/v3.13/community >> /etc/apk/repositories
> apk update
> apk del --rdepends python3 # removes everything using python3.9
> apk add python3\<3.9 py3-numpy\<1.20 py3-pip # installs python3.8
> ```

Is there a way to install matplotlib or any other packages in the path of /usr/lib/python3.8/site-packages/ ?
Because everything that is installed using apk add py3-xxx would go to /usr/lib/python3.9/site-packages/ and when running the script importing that module it returns module not found. Currently only numpy is installed in python3.8.

I even tried using pip to install the package rather than apk pre-built binary (python3.8 -m pip install --target=/usr/lib/python3.8/site-packages matplotlib) but it returns error that supposedly some required dependancies are missing like fortran, gcc and etc. It's impossible to install a package using python pip, needless to say it is super slow in iSH shell as well.

**Comment by dannytoomey** [comment]
> This fixes numpy, but it appears to break pip:
> 
> `# pip -v Traceback (most recent call last): File "/usr/bin/pip", line 33, in <module> sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip')()) File "/usr/bin/pip", line 22, in importlib_load_entry_point for entry_point in distribution(dist_name).entry_points File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution return Distribution.from_name(distribution_name) File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name raise PackageNotFoundError(name) importlib.metadata.PackageNotFoundError: pip`

I was able to resolve this issue with 
`python3 -m ensurepip` after running the same commands. So, the full command that got numpy to work without breaking pip was
```
echo https://dl-cdn.alpinelinux.org/alpine/v3.13/main >> /etc/apk/repositories
echo https://dl-cdn.alpinelinux.org/alpine/v3.13/community >> /etc/apk/repositories
apk update
apk del --rdepends python3 # removes everything using python3.9
apk add python3\<3.9 py3-numpy\<1.20 py3-pip 
python3 -m ensurepip
```
