### ISSUE TITLE
Secrets package

### ISSUE THREAD

**Issue by ThienVie** [ish-app/ish#1839]
Hello, I want to ask you how I can install secrets package, so I can write
```
python
import secrets
```
I tried to write
`pip install secrets`,
after `apk add python3`
and `pip3 install --upgrade pip`.
But the output is:
```

Collecting secrets
  Using cached secrets-1.0.2.tar.gz (7.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-806pa1ep/secrets_87c217c6f5da4f87b6f143e83be2f6c8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-806pa1ep/secrets_87c217c6f5da4f87b6f143e83be2f6c8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0tq_dapj
         cwd: /tmp/pip-install-806pa1ep/secrets_87c217c6f5da4f87b6f143e83be2f6c8/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-806pa1ep/secrets_87c217c6f5da4f87b6f143e83be2f6c8/setup.py", line 10, in <module>
        import OpenSSL
    ModuleNotFoundError: No module named 'OpenSSL'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-806pa1ep/secrets_87c217c6f5da4f87b6f143e83be2f6c8/setup.py", line 12, in <module>
        raise ImportError('Installing this module requires OpenSSL python bindings')
    ImportError: Installing this module requires OpenSSL python bindings
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/93/c4/166925e31bc06bfe49deb4dc3922584790a33b897509bac388acdc074a60/secrets-1.0.2.tar.gz#sha256=37075ab08607092e76da2b86e94dd38a0216ec80088a0a3f9220077750aeddf9 (from https://pypi.org/simple/secrets/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement secrets
ERROR: No matching distribution found for secrets
```
Do you know what happened? This/That output is too much for me to understand.

**Comment by ifuchs** [comment]
I just tried ‘import secrets’ (without installing anything) and it seemed
to work without error. Did you try that?

**Comment by ThienVie** [comment]
Thank you very much. <3
