### ISSUE TITLE
Running `gh repo clone repoName` (github-cli) results with error

### ISSUE THREAD

**Issue by andynameistaken** [ish-app/ish#2205]
```
Andrzejs-iPad:~# apk add github-cli
(1/8) Installing ca-certificates (20230506-r0)
(2/8) Installing brotli-libs (1.0.9-r5)
(3/8) Installing nghttp2-libs (1.43.0-r0)
(4/8) Installing libcurl (8.0.1-r0)
(5/8) Installing expat (2.5.0-r0)
(6/8) Installing pcre2 (10.36-r1)
(7/8) Installing git (2.32.7-r0)
(8/8) Installing github-cli (2.1.0-r1)
Executing busybox-1.33.1-r8.trigger
Executing ca-certificates-20230506-r0.trigger
OK: 49 MiB in 22 packages
Andrzejs-iPad:~# gh repo clone andynameistaken/testrepo
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigpanic called from 0x1
stack: frame={sp:0xffffdc2c, fp:0xffffdc44} stack=[0x58402000,0x5840a000)

runtime.throw(0x570adcc9, 0x2a)
        runtime/panic.go:1117 +0x70
runtime: unexpected return pc for runtime.sigpanic called from 0x1
stack: frame={sp:0xffffdc2c, fp:0xffffdc44} stack=[0x58402000,0x5840a000)

runtime.sigpanic()
        runtime/signal_unix.go:718 +0x269

goroutine 35 [running]:
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x566f6f90]

goroutine 0 [idle]:
runtime: unexpected return pc for runtime.sigpanic called from 0x1
stack: frame={sp:0xffffdc2c, fp:0xffffdc44} stack=[0x58402000,0x5840a000)

runtime.throw(0x570adcc9, 0x2a)
        runtime/panic.go:1117 +0x70
runtime.sigpanic()
        runtime/signal_unix.go:718 +0x269
runtime.gentraceback(0xffffffff, 0xffffffff, 0x0, 0x584822a0, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, ...)
        runtime/traceback.go:239 +0x1040
runtime.traceback1(0xffffffff, 0xffffffff, 0x0, 0x584822a0, 0x0)
        runtime/traceback.go:732 +0xfc
runtime.traceback(...)
        runtime/traceback.go:686
runtime.tracebackothers(0x584008c0)
        runtime/traceback.go:924 +0x249
runtime.dopanic_m(0x584008c0, 0x566d3610, 0xffffdc18, 0x5817a6b8)
        runtime/panic.go:1317 +0x290
runtime.fatalthrow.func1()
        runtime/panic.go:1172 +0x4c
runtime.fatalthrow()
        runtime/panic.go:1169 +0x60
runtime.throw(0x570adcc9, 0x2a)
        runtime/panic.go:1117 +0x70
runtime: unexpected return pc for runtime.sigpanic called from 0x1
stack: frame={sp:0xffffdc2c, fp:0xffffdc44} stack=[0x58402000,0x5840a000)

runtime.sigpanic()
        runtime/signal_unix.go:718 +0x269
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0xffffffd8 pc=0x58123766]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x58123766
stack: frame={sp:0xffffda68, fp:0xffffda80} stack=[0xfffdec98,0xffffdce0)
ffffd9e8:  566d3c35 <runtime.dopanic_m+501>  566d3610 <runtime.throw+112>  ffffda54  00000000 
ffffd9f8:  58166140  010050fb  0000001f  566d3979 <runtime.startpanic_m+249> 
ffffda08:  58123766  ffffffd8  00000001  5709e991 
ffffda18:  566ff18c <runtime.fatalthrow.func1+76>  58166140  566d3610 <runtime.throw+112>  ffffda54 
ffffda28:  00000001  ffffda54  566d3610 <runtime.throw+112>  58166140 
ffffda38:  566d37d0 <runtime.fatalthrow+96>  ffffda40  566ff140 <runtime.fatalthrow.func1+0>  58166140 
ffffda48:  566d3610 <runtime.throw+112>  ffffda54  566d3610 <runtime.throw+112>  ffffda58 
ffffda58:  566ff0d0 <runtime.throw.func1+0>  570adcc9  0000002a  566ea1e9 <runtime.sigpanic+617> 
ffffda68: <570adcc9  0000002a  566d50e5 <runtime.printunlock+5>  566d5049 <runtime.recordForPanic+281> 
ffffda78:  58166140 !58123766 >00000000  566d6497 <runtime.gopark+247> 
ffffda88:  00000000  00000000  00000000  00000014 
ffffda98:  00000000  00000000  00000000  00000000 
ffffdaa8:  566f7e2c <runtime.traceback1+252>  ffffffff  ffffffff  00000000 
ffffdab8:  584822a0  00000000  00000000  00000064 
ffffdac8:  00000000  00000000  00000000  00000000 
ffffdad8:  00000000  566d508b <runtime.printlock+27>  566d50fb <runtime.printunlock+27>  566d50e5 <runtime.printunlock+5> 
ffffdae8:  566d5049 <runtime.recordForPanic+281>  5817a728  00000002  00000000 
ffffdaf8:  00000000  00000000 
runtime.throw(0x570adcc9, 0x2a)
        runtime/panic.go:1117 +0x70
runtime: unexpected return pc for runtime.sigpanic called from 0x58123766
stack: frame={sp:0xffffda68, fp:0xffffda80} stack=[0xfffdec98,0xffffdce0)
ffffd9e8:  566d3c35 <runtime.dopanic_m+501>  566d3610 <runtime.throw+112>  ffffda54  00000000 
ffffd9f8:  58166140  010050fb  0000001f  566d3979 <runtime.startpanic_m+249> 
ffffda08:  58123766  ffffffd8  00000001  5709e991 
ffffda18:  566ff18c <runtime.fatalthrow.func1+76>  58166140  566d3610 <runtime.throw+112>  ffffda54 
ffffda28:  00000001  ffffda54  566d3610 <runtime.throw+112>  58166140 
ffffda38:  566d37d0 <runtime.fatalthrow+96>  ffffda40  566ff140 <runtime.fatalthrow.func1+0>  58166140 
ffffda48:  566d3610 <runtime.throw+112>  ffffda54  566d3610 <runtime.throw+112>  ffffda58 
ffffda58:  566ff0d0 <runtime.throw.func1+0>  570adcc9  0000002a  566ea1e9 <runtime.sigpanic+617> 
ffffda68: <570adcc9  0000002a  566d50e5 <runtime.printunlock+5>  566d5049 <runtime.recordForPanic+281> 
ffffda78:  58166140 !58123766 >00000000  566d6497 <runtime.gopark+247> 
ffffda88:  00000000  00000000  00000000  00000014 
ffffda98:  00000000  00000000  00000000  00000000 
ffffdaa8:  566f7e2c <runtime.traceback1+252>  ffffffff  ffffffff  00000000 
ffffdab8:  584822a0  00000000  00000000  00000064 
ffffdac8:  00000000  00000000  00000000  00000000 
ffffdad8:  00000000  566d508b <runtime.printlock+27>  566d50fb <runtime.printunlock+27>  566d50e5 <runtime.printunlock+5> 
ffffdae8:  566d5049 <runtime.recordForPanic+281>  5817a728  00000002  00000000 
ffffdaf8:  00000000  00000000 
runtime.sigpanic()
        runtime/signal_unix.go:718 +0x269
fatal error: unlock of unlocked lock
stack trace unavailable
```

**Comment by Murtadha98-cybe** [comment]
I'm
