### ISSUE TITLE
Mosh exits after connecting

### ISSUE THREAD

**Issue by NightMachinary** [ish-app/ish#710]
```
❯ mosh eva@x.x.x.x




mosh did not shut down cleanly. Please note that the
mosh-server process may still be running on the server.
[mosh is exiting.]
❯ dmesg 
[    0.000000] 73 stub syscall 375
               76 stub syscall 375
               92 stub syscall 375
               95 stub syscall 375
```

**Comment by tbodt** [comment]
Works on my machine

**Comment by wasbazi** [comment]
I’m also seeing this issue on my iPad, though not sure what debug data is helpful

**Comment by joefitzgerald** [comment]
Also seeing a bunch of `nnn stub syscall 375` in the dmesg output after `go build ./...` fails for git `clone https://github.com/maxbrunsfeld/counterfeiter && cd counterfeiter && go build ./...`.

See: https://github.com/maxbrunsfeld/counterfeiter

```

# go build ./...
go: downloading golang.org/x/tools v0.0.0-20200508184754-b8469989bc69
go: downloading golang.org/x/mod v0.2.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
# github.com/maxbrunsfeld/counterfeiter/v6/generator
generator/fake.go:106:7: internal compiler error: 'unexport': panic during regalloc while compiling unexport:

runtime error: index out of range [35] with length 82

goroutine 1 [running]:
cmd/compile/internal/ssa.Compile.func1(0x94a7304, 0x998b740)
        /usr/lib/go/src/cmd/compile/internal/ssa/compile.go:47 +0x87
panic(0x89b26a0, 0x99f6110)
        /usr/lib/go/src/runtime/panic.go:969 +0x122
cmd/compile/internal/ssa.(*Func).getHome(...)
        /usr/lib/go/src/cmd/compile/internal/ssa/stackalloc.go:353
cmd/compile/internal/ssa.(*regAllocState).regalloc(0x97e7790, 0x998b740)
        /usr/lib/go/src/cmd/compile/internal/ssa/regalloc.go:1426 +0x77d3
cmd/compile/internal/ssa.regalloc(0x998b740)
        /usr/lib/go/src/cmd/compile/internal/ssa/regalloc.go:146 +0x4f
cmd/compile/internal/ssa.Compile(0x998b740)
        /usr/lib/go/src/cmd/compile/internal/ssa/compile.go:92 +0x87d
cmd/compile/internal/gc.buildssa(0x9467c70, 0x0, 0x0)
        /usr/lib/go/src/cmd/compile/internal/gc/ssa.go:445 +0xa72
cmd/compile/internal/gc.compileSSA(0x9467c70, 0x0)
        /usr/lib/go/src/cmd/compile/internal/gc/pgen.go:298 +0x52
cmd/compile/internal/gc.compile(0x9467c70)
        /usr/lib/go/src/cmd/compile/internal/gc/pgen.go:277 +0x2c7
cmd/compile/internal/gc.funccompile(0x9467c70)
        /usr/lib/go/src/cmd/compile/internal/gc/pgen.go:222 +0xad
cmd/compile/internal/gc.Main(0x8a00360)
        /usr/lib/go/src/cmd/compile/internal/gc/main.go:714 +0x2e03
main.main()
        /usr/lib/go/src/cmd/compile/main.go:52 +0x93

Please file a bug report including a short program that triggers the error.
https://golang.org/issue/new
^C
Joes-iPad-Pro-129-2020:~/counterfeiter# dmesg
16 stub syscall 375
22 stub syscall 375
[...]
```

**Comment by tbodt** [comment]
@joefitzgerald That seems like an unrelated problem, could you open a new issue?

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/101841575-2d47d880-3b14-11eb-9ebf-89ac6edab30b.jpeg)
