### ISSUE TITLE
[Go] kubectl crash on any subcommand

### ISSUE THREAD

**Issue by LukeChannings** [ish-app/ish#756]
The kubectl binary itself runs correctly, but running any subcommand crashes with this error:

```
> kubectl cluster-info
SIGILL: illegal instruction
PC=0x85721ce m=3 sigcode=128

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/flowcontrol.NewTokenBucketRateLimiter(...)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/flowcontrol/throttle.go:54
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.UnversionedRESTClientFor(0xaf91b24, 0x0, 0x0, 0x21)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/config.go:373 +0x59e fp=0xaf91b08 sp=0xaf91a38 pc=0x85721ce
k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.NewDiscoveryClientForConfig(0xaf22b00, 0x2, 0x2, 0xaa9bce0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/discovery_client.go:489 +0x5d fp=0xaf91c24 sp=0xaf91b08 pc=0x8c2085d
k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached/disk.NewCachedDiscoveryClientForConfig(0xaf22900, 0xaee8630, 0x2a, 0xac51d20, 0x16, 0xb2c97000, 0x8b, 0xe7d3d430, 0x50, 0x0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached/disk/cached_discovery.go:283 +0x31 fp=0xaf91c48 sp=0xaf91c24 pc=0x8ce9441
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions.(*ConfigFlags).ToDiscoveryClient(0xa8372c0, 0x0, 0x0, 0x8, 0x2e0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go:256 +0x158 fp=0xaf91ca4 sp=0xaf91c48 pc=0x8d06228
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.(*MatchVersionFlags).ToDiscoveryClient(0xaadad40, 0xaa7b410, 0xe7d3d430, 0xaa7b3f8, 0x80b6b33)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/kubectl_match_version.go:91 +0x5a fp=0xaf91cbc sp=0xaf91ca4 pc=0x8ded7ba
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.NewBuilder.func1(0xacc7cf4, 0x811bdcb, 0x94437ad, 0x808888f)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/builder.go:183 +0x27 fp=0xaf91ce4 sp=0xaf91cbc pc=0x8cd8dd7
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*cachingCategoryExpanderFunc).ToCategoryExpander(0xabf0ee0, 0x0, 0x0, 0x0, 0x0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/builder.go:1187 +0x94 fp=0xaf91d1c sp=0xaf91ce4 pc=0x8cd05c4
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*cachingCategoryExpanderFunc).ToCategoryExpander-fm(0x94437ad, 0x8, 0x943d49f, 0x1)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/builder.go:1180 +0x20 fp=0xaf91d34 sp=0xaf91d1c pc=0x8cdb5f0
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*Builder).ReplaceAliases(0xaf6c9a0, 0x94437ad, 0x8, 0xacc7e00, 0x0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/builder.go:583 +0xb2 fp=0xaf91da4 sp=0xaf91d34 pc=0x8ccc0c2
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*Builder).ResourceTypeOrNameArgs(0xaf6c9a0, 0x9469c00, 0xaf91e3c, 0x1, 0x1, 0xaf6c9a0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/builder.go:553 +0x905 fp=0xaf91e14 sp=0xaf91da4 pc=0x8ccbfb5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/clusterinfo.(*ClusterInfoOptions).Run(0xae5e210, 0x0, 0x95206e4)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/clusterinfo/clusterinfo.go:100 +0xd8 fp=0xaf91e48 sp=0xaf91e14 pc=0x8ede0c8
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/clusterinfo.NewCmdClusterInfo.func1(0xaf25b80, 0xa5cc380, 0x0, 0x0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/clusterinfo/clusterinfo.go:70 +0x64 fp=0xaf91e68 sp=0xaf91e48 pc=0x8ee0204
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xaf25b80, 0xa5cc380, 0x0, 0x0, 0xaf25b80, 0xa5cc380)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x1ed fp=0xaf91ed0 sp=0xaf91e68 pc=0x835199d
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xac3f2c0, 0xa86a030, 0xa80c040, 0x2)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x251 fp=0xaf91f38 sp=0xaf91ed0 pc=0x8352251
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1dc fp=0xaf91fb0 sp=0xaf91f38 pc=0x91358ac
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x202 fp=0xaf91ff0 sp=0xaf91fb0 pc=0x80751b2
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1325 +0x1 fp=0xaf91ff4 sp=0xaf91ff0 pc=0x809d491

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0xa5ba0a0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1010 +0x6b
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:411 +0xe3

goroutine 9 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x12f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x1a
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x37

goroutine 10 [runnable]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.NewJitteredBackoffManager(...)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:363
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x9520688, 0x2a05f200, 0x1, 0x0, 0x0, 0x1, 0xa85e0c0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x27
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x9520688, 0x2a05f200, 0x1, 0xa85e0c0)
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x47
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
	/workspace/anago-v1.18.3-beta.0.58+d6e40f410ca91c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x81

eax    0xaf92000
ebx    0x44
ecx    0xa8000e0
edx    0x0
edi    0x2
esi    0xf1
ebp    0xaf92000
esp    0xaf91a38
eip    0x85721ce
eflags 0x202
cs     0x0
fs     0x0
gs     0x0
```

dmesg:

```
23 illegal instruction at 0x85721ce: f3 0f 5a c8 8b 44 24 04 
28 illegal instruction at 0x85721ce: f3 0f 5a c8 8b 44 24 04 
32 illegal instruction at 0x85721ce: f3 0f 5a c8 8b 44 24 04 
```

**Comment by tbodt** [comment]
How did you install kubectl?

**Comment by LukeChannings** [comment]
```
curl -OL https://dl.k8s.io/v1.18.3/kubernetes-client-linux-386.tar.gz
tar xf kubernetes-client-linux-386.tar.gz
./kubernetes/client/bin/kubectl
```

The default install script will download a 64-bit binary that is incompatible.

**Comment by garretruh** [comment]
I encountered a slightly different error running kubectl:

<details>
  <summary>Output</summary>

```sh
$ kubectl cluster-info
SIGILL: illegal instruction
PC=0x85aa97b m=0 sigcode=128

goroutine 1 [running, locked to thread]:
k8s.io/kubernetes/vendor/google.golang.org/protobuf/reflect/protoreflect.ValueOfFloat32(0x0, 0x0, 0x92b86c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go:124 +0x1b fp=0xa85beac sp=0xa85bea0 pc=0x85aa97b
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.init()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/convert.go:84 +0x71b fp=0xa85bed4 sp=0xa85beac pc=0x864301b
runtime.doInit(0xa4edd20)
        /usr/local/go/src/runtime/proc.go:5222 +0x6a fp=0xa85bee8 sp=0xa85bed4 pc=0x808034a
runtime.doInit(0xa4e5e40)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85befc sp=0xa85bee8 pc=0x8080323
runtime.doInit(0xa4e3440)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf10 sp=0xa85befc pc=0x8080323
runtime.doInit(0xa4ec960)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf24 sp=0xa85bf10 pc=0x8080323
runtime.doInit(0xa4eca20)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf38 sp=0xa85bf24 pc=0x8080323
runtime.doInit(0xa4e7700)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf4c sp=0xa85bf38 pc=0x8080323
runtime.doInit(0xa4effc0)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf60 sp=0xa85bf4c pc=0x8080323
runtime.doInit(0xa4edc20)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf74 sp=0xa85bf60 pc=0x8080323
runtime.doInit(0xa4e4fc0)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf88 sp=0xa85bf74 pc=0x8080323
runtime.doInit(0xa4f0de0)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bf9c sp=0xa85bf88 pc=0x8080323
runtime.doInit(0xa4e7f40)
        /usr/local/go/src/runtime/proc.go:5217 +0x43 fp=0xa85bfb0 sp=0xa85bf9c pc=0x8080323
runtime.main()
        /usr/local/go/src/runtime/proc.go:190 +0x1be fp=0xa85bff0 sp=0xa85bfb0 pc=0x807516e
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1325 +0x1 fp=0xa85bff4 sp=0xa85bff0 pc=0x809d491

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0xa6b9d60)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1107 +0x6b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xe3

eax    0x0
ebx    0x0
ecx    0xa8000e0
edx    0x92b86c0
edi    0xa8c875f
esi    0xa85becb
ebp    0xa8c8767
esp    0xa85bea0
eip    0x85aa97b
eflags 0x206
cs     0x0
fs     0x0
gs     0x0
```
```
$ dmesg
16 illegal instruction at 0x85aa97b: f3 0f 5a c0 f2 0f 11 04
```
</details>

Was subsequently able to get it working by doing a custom build with `GO386=387` set (added to the build script [here](https://github.com/kubernetes/kubernetes/blob/6dbb92de3d06a241d89f599f31a425672d9d7d40/hack/lib/golang.sh#L708)).
